### ISSUE TITLE
GraphQL schema update CI requires access to create Pull Requests

### ISSUE THREAD

**Issue by Spiker985** [pulsar-edit/github#20]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

![image](https://user-images.githubusercontent.com/7829451/224462866-fe51aee3-92bd-403e-9e30-dda8e3c0c8d3.png)

### Pulsar version

N/A

### Which OS does this happen on?

🐧 Debian based (Linux Mint, Ubuntu, etc.)

### OS details

N/A

### Which CPU architecture are you running this on?

None

### What steps are needed to reproduce this?

The settings within the `github` package GitHub repository, need updating so that actions can open Pull Requests.

![image](https://user-images.githubusercontent.com/7829451/224463037-56276053-b96b-4091-9a69-3c8d8bfdd031.png)

The section would be under https://github.com/pulsar-edit/github/settings/actions

**Comment by Spiker985** [comment]
@pulsar-edit/core-admin Does someone want to enable that setting, so that the GraphQL CI will work appropriately?

**Comment by confused-Techie** [comment]
@Spiker985 thanks for pinging me like this. Was super helpful to get it resolved.

Turns out this setting was disabled on this repo, because it was off on our org.

I've gone ahead and enabled it for the org which allows us to turn on or off the setting here. Which I've gone ahead and turned it on.

Thanks for this!
