### ISSUE TITLE
Add `pulsar-package` and `pulsar-edit` topic

### ISSUE THREAD

**Issue by Sertonix** [pulsar-edit/github#6]
### Have you checked for existing feature requests?

- [X] Completed

### Summary

As discussed [here](https://github.com/orgs/pulsar-edit/discussions/69#discussioncomment-4401556) this package should have the topics `pulsar-package` and `pulsar-edit`.

### Enter your response below:

It would be easier to find pulsar related repositories on github.

**Comment by confused-Techie** [comment]
Great call, I've added them here, thanks!
